spring:
    flyway:
        baseline-on-migrate: true
    h2.console:
        enabled: true
        path: '/console'
    datasource :
        url : 'jdbc:h2:file:~\IdeaProjects\demoMASSpring\mas_project_database.db'
    jpa:
        hibernate:
            ddl-auto: validate


