spring:
    flyway:
        baseline-on-migrate: true
    h2.console:
        enabled: true
        path: '/console'
    datasource :
        url : 'jdbc:h2:file:~/IdeaProjects/demoMASSpring/demo.db'
    jpa:
        hibernate:
            ddl-auto: validate

